### ISSUE TITLE
Injector could be used lazy as a descriptor.

### ISSUE THREAD

**Issue by proofit404** [proofit404/dependencies#312]
```python
class Foo:
    user = ~Injector(user=User, name='x')

    def foo(self):
        self.user  # is an instance of the User
        self.user.name # is equal 'x'
```

**Comment by wasinski** [comment]
wouldn't this be an implementation of the service locator pattern? Class Foo instead of being build with a passed User class dependency (DI pattern) receives a _static, globally available service locator which then can be used to fetch needed dependencies_. SL pattern introduces a lot of problems and favors poor design. https://en.wikipedia.org/wiki/Service_locator_pattern

**Comment by proofit404** [comment]
Hi Tomasz,

Thanks for the comment!

My first intention for this functionality was simplification of class-based views in frameworks like Django and Flask.

Such classes could not have proper dependency injection since its design based on the inheritance.

After your comment I see that this feature could be abused in other parts of the system.

It not worth to implement it.

Thanks for the suggestion!

Have a wonderful day :palm_tree: 

Regards,
Artem.
