### ISSUE TITLE
Best practice for sharing dependencies in this case?

### ISSUE THREAD

**Issue by Synocode** [proofit404/dependencies#535]
I'm facing the following problem; I have multiple classes which depend on QueryHandler instances. Depending on the strategy associated with a query, the instantiation of its corresponding QueryHandler's dependencies are deferred to a nested Injector subclass. I would like to inject the same QueryHandler instance into all classes which are using the same strategy.  I only want to instantiate a single QueryHandler per strategy (in the code below, Mongo or Mysql) and inject it into the service classes which, currently are each initialized with a new QueryHandler instance. Not all strategies will necessarily have an instantiated QueryHandler over the course of a single run of the application.

Any advice on how to achieve this type of dependency sharing is appreciated.

```python
class QueryHandler:
    __init__(self, query_resolver, query_responder, response_handler): ...

class MongoQueryResponder:
    __init__(self, mongo_client): ...

class MysqlQueryResponder:
    __init__(self, mysql_client): ...

class MongoClient
    __init__(self, mongo_connection_details): ...

class MysqlClient
    __init__(self, mysql_connection_details): ...

class MongoQHComposer(Injector):
    query_handler = QueryHandler

    response_handler = ModelBasedResponseHandler
    query_responder = MongoQueryResponder
    mongo_client = MongoCli

class MysqlQHComposer(Injector):
    query_handler = QueryHandler

    response_handler = MysqldResponseHandler
    query_responder = MysqloQueryResponder
    mysql_client = MysqlCli

class QueryHandlerComposer(Injector)
    @value
    def query_handler(strategy, settings):
        if strategy == 'mongo':
            from composers.mongo_qh_composer import MongoQHComposer
            return MongoQHComposer(settings=settings).query_handler
        elif strategy == 'mysql':
            from composers.mysyql_qh_composer import MysqlQHComposer
            return MysqlQHComposer(settings=settings).query_handler

    strategy = (this << 1).strategy
    settings = (this << 1).settings
```

**Comment by Synocode** [comment]
Linked comment may be sufficient to do what I want, but I would still be happy to hear better alternatives if they exist.

https://github.com/proofit404/dependencies/issues/298#issuecomment-656201022

**Comment by proofit404** [comment]
Hello, thank you for using `dependencies` library :wave:

Sorry for late response, I was traveling on the weekend.

Generally, if you would like to introduce any kind of `if` condition to the injection process you have two options:
1. Do it inside `Injector` using `@value` decorator
2. Do it in the client code choosing different `Injector` sub-classes.

I would prefer first one, since it would be easier to archive your goal of sharing instances.

Note that `Injector` would instantiate its attribute once during dependency injection process.

So, if `Composer` attribute `a` depends on `b` and `c`, when both `b` and `c` depends on `d` at the same time, attribute access on `a` would instantiate `d` once. And both `b` and `c` would share the same instance of `d`.

This rule makes it perfect candidate for you problem, but `@value` should not import other injectors inside its function.

```python
from dependencies import Injector, Package, this

composers  = Package('composers')

class QueryHandlerComposer(Injector)
    @value
    def query_handler(strategy, mongo_handler, mysql_handler):
        return {'mongo': mongo_handler, 'mysql': mysql_handler}[strategy]

    mongo_handler = composers.mongo_qh_composer.MongoQHComposer.query_handler
    mysql_handler = composers.mysyql_qh_composer.MysqlQHComposer.query_handler
    strategy = (this << 1).strategy
    settings = (this << 1).settings
```

Yes, this would instantiate both mongo and mysql handlers no matter what strategy was specified, and select from two instances based on it later. This could cause problems if you have poorly written classes which do network connection in the constructor. But generally, it's not the problem with any kind of adequate connection pools.

https://github.com/proofit404/dependencies/issues/298#issuecomment-656201022 on the other hand would be useful if you would like to keep same instance of query handler between separate `Injector` access.

```python
class Container(Injector):
    class foo:
        def __init__(self, bar):
            self.bar = bar

    @value
    @lru_cache
    def bar():
        return random.randint()

Container.foo.bar == Container.foo.bar  # would be the same
```

So it became a variant of singleton pattern in this case. I suggest to avoid it as far as possible.

For example, if you need to use same instances within some kind of bound context (http request handler, celery task) we have a better tool for it: [sticky scopes](https://proofit404.github.io/dependencies/sticky/)

So, you would need singleton **only** if you need to share instances between different http request, which is also an antipattern in most cases.

Hope my explanation could point you in the right direction :pray: 

If you have more questions, or would like to have further discussion feel free to reopen this issue.

Have a good day! :palm_tree: :cocktail: 

Best regards,
Artem.
